filter:
    paths: ["src/*"]
tools:
    external_code_coverage: true
    php_code_coverage: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_mess_detector:
        enabled: true
        config:
            ruleset: ./phpmd.xml
    php_code_sniffer:
        enabled: true
        config:
            ruleset: ./phpcs.xml
build:
    environment:
        mysql: 5.6
    dependencies:
        before:
            - 'vendor/bin/composer env'
            - 'vendor/bin/composer setup'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'src/*'
                    format: 'clover'