filter:
    paths: ["src/*"]
tools:
    external_code_coverage: 
        timeout: 600
        runs: 3
    php_code_coverage: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_mess_detector:
        enabled: true
        config:
            ruleset: ./phpmd.xml
    php_code_sniffer:
        enabled: true
        config:
            ruleset: ./phpcs.xml
build:
    environment:
        mysql: 5.6
    dependencies:
        after:
            - 'vendor/bin/composer env'
            - 'vendor/bin/composer setup'
