language: php
php:
  - 5.5
  - 5.6
  - 7

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source
  - vendor/bin/composer env
  - vendor/bin/composer setup

script:
  - vendor/bin/phpunit

after_script:
#  - php ocular.phar code-coverage:upload --access-token=SCRUTINIZER_ACCESS_TOKEN --format=php-clover build/logs/clover.xml
